version: '3'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/manus_manager
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_REDIRECT_URI=http://localhost:3000/auth/google/callback
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - manus-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - manus-network

  # Database service
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manus_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - manus-network

networks:
  manus-network:
    driver: bridge

volumes:
  postgres_data:
