name: manus-bridge
region: sfo
services:
- name: manus-bridge-api
  github:
    branch: master
    deploy_on_push: true
    repo: designdream/hack-manus
  source_dir: manus-bridge
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-s
  routes:
  - path: /
  envs:
  - key: MANUS_BRIDGE_API_HOST
    value: 0.0.0.0
  - key: MANUS_BRIDGE_API_PORT
    value: "8080"
  - key: MANUS_OPT_PATH
    value: "./data/opt"
  - key: MANUS_OPT2_PATH
    value: "./data/opt2"
  - key: MANUS_OPT3_PATH
    value: "./data/opt3"
  - key: MANUS_BRIDGE_DB_URL
    value: "sqlite:///manus_bridge.db"
  build_command: apt-get update && apt-get install -y chromium-browser && pip install -e .
  run_command: python run.py
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONPATH
    value: "."
  - key: DISPLAY
    value: ":99"
  - key: CHROME_BIN
    value: "/usr/bin/chromium-browser"
